### ISSUE TITLE
Faulty formatting of documentation on npm 

### ISSUE THREAD

**Issue by Dolers** [QuorumDMS/ftp-srv#301]
Hi!

I've noticed that the formatting on npm.io (https://npm.io/package/ftp-srv) has some issues starting from pasv_url parameter's description. The example codeblock ends early and starting a new codeblock at the end of it.

**Comment by matt-forster** [comment]
Hi @Dolers, npm.io is an independent website that parses information from the npm registry. As such, it is their responsibility to render the markdown correctly.

Looking at two other sources - the [readme file here on github](https://github.com/QuorumDMS/ftp-srv#readme), and the [official NPM documentation](https://www.npmjs.com/package/ftp-srv), the markdown is correct. Feel free to contact npm.io directly to raise the issue with them;

![image](https://user-images.githubusercontent.com/3375444/168632944-c4e421d5-403c-4c2b-bd1a-cdb1242552c6.png)

**Comment by Dolers** [comment]
Thanks!
I don't know how they managed to become listed before official npm documentation.
