### ISSUE TITLE
errors is not defined

### ISSUE THREAD

**Issue by soshimee** [QuorumDMS/ftp-srv#315]
It keeps saying errors is not defined and failing.

**Comment by soshimee** [comment]
Nevermind, I'm dumb

**Comment by camille68** [comment]
Same issue for me while using anonymous login both on Windows and raspberry pi

**Comment by iakashpatel** [comment]
actually if you are using sample code from npm/git you need to correct `error` variable as error is not defined.

```
return reject(new Error("Invalid username or password", 401));
```

instead of 

```
return reject(new errors.GeneralError('Invalid username or password', 401));
```
