### ISSUE TITLE
virtual file system

### ISSUE THREAD

**Issue by Andromeda606** [QuorumDMS/ftp-srv#350]
I want to delete and edit files with database, not file in ftp connection. However, stream is always used and no output is given to me directly. Let me give an example

```JS
class MyFileSystem extends FileSystem {
async write(fileName: string, {append, start}: { append?: boolean; start?: any }): any {
        console.log("write",append,start);
        const date = new Date().toISOString();
        let data = await this.read(fileName,{status: true, start:undefined});
        console.log("data",data);
        if(data === null){
            data = "";
        }
        console.log(await createFile({
            name: fileName,
            dev: parseInt(String(Math.random() * 1000)),
            ino: parseInt(String(Math.random() * 1000)),
            mode: parseInt(String(Math.random() * 1000)),
            nlink: 1,
            uid: 0,
            gid: 0,
            rdev: 0,
            size: parseInt(String(Math.random() * 1000)),
            blksize: parseInt(String(Math.random() * 1000)),
            blocks: 8,
            atime: date,
            mtime: date,
            ctime: date,
            birthtime: date,
            isDirectory: () => false
        }, this.currentDirectory(), data))

        //const stream = createWriteStream("/tmp/AS.txt",start);
        //return Promise.resolve(stream);
        //return super.write(fileName, {append, start});
    }
```
As you can see, I wrote inside the filesystem class. But the program gives an error unless there is a return stream. What I want is data to be written directly without using fs

https://github.com/QuorumDMS/ftp-srv/blob/main/src/commands/registration/retr.js
do i need to edit this file to do what i want? is there any other way?

Why do I want this?

I want it because the files will actually be accessed via an http request and not via ftp. In short, when the person tries to open the "foo.txt" file, the output in the "https://bar.foo/foo.txt" link will be given. If the person wants to write data, the same actions will take place like this

**Comment by Aschen** [comment]
@Andromeda606 Here is a simple example of overriding the `write` method to send the file into another system like a database for example:

```js
  write() {
    const stream = new PassThrough();
    let buffer;

    stream.on("data", (chunk: Buffer) => {
      buffer = Buffer.concat([chunk]);
    });

    stream.once("error", (error) => {
      // do something with the error
    });

    stream.once("close", () => {
      // do something with "buffer" who contain the file content
      // for example it could
    });

    return {
      stream,
    };
  }
```

The stream you are returning is written on by `ftp-srv`, chunk by chunk with the uploaded file content. When the entire file has been downloaded, you can send it to your database.

**Comment by Andromeda606** [comment]
> @Andromeda606 Here is a simple example of overriding the `write` method to send the file into another system like a database for example:
> 
> ```js
>   write() {
>     const stream = new PassThrough();
>     let buffer;
> 
>     stream.on("data", (chunk: Buffer) => {
>       buffer = Buffer.concat([chunk]);
>     });
> 
>     stream.once("error", (error) => {
>       // do something with the error
>     });
> 
>     stream.once("close", () => {
>       // do something with "buffer" who contain the file content
>       // for example it could
>     });
> 
>     return {
>       stream,
>     };
>   }
> ```
> 
> The stream you are returning is written on by `ftp-srv`, chunk by chunk with the uploaded file content. When the entire file has been downloaded, you can send it to your database.

I forked the library. https://github.com/Andromeda606/ftp-srv thank you anyway

**Comment by Aschen** [comment]
> > @Andromeda606 Here is a simple example of overriding the `write` method to send the file into another system like a database for example:
> > ```js
> >   write() {
> >     const stream = new PassThrough();
> >     let buffer;
> > 
> >     stream.on("data", (chunk: Buffer) => {
> >       buffer = Buffer.concat([chunk]);
> >     });
> > 
> >     stream.once("error", (error) => {
> >       // do something with the error
> >     });
> > 
> >     stream.once("close", () => {
> >       // do something with "buffer" who contain the file content
> >       // for example it could
> >     });
> > 
> >     return {
> >       stream,
> >     };
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The stream you are returning is written on by `ftp-srv`, chunk by chunk with the uploaded file content. When the entire file has been downloaded, you can send it to your database.
> 
> I forked the library. https://github.com/Andromeda606/ftp-srv thank you anyway

Ok :+1: You can close the issue then I suppose
