### ISSUE TITLE
Disable Delete command

### ISSUE THREAD

**Issue by christophe77** [QuorumDMS/ftp-srv#357]
Is there a way to disable the delete command? I don't want the users to be able to delete files.

**Comment by lucasantoiemma** [comment]
Hi @christophe77 have you tried to pass the option _blacklist = ["DELE", "RMD"]_?
DELE to avoid file deletion
RMD to avoid folder deletion
Let me know if it worked! Enjoy your day!

**Comment by christophe77** [comment]
> Hi @christophe77 have you tried to pass the option _blacklist = ["DELE", "RMD"]_? DELE to avoid file deletion RMD to avoid folder deletion Let me know if it worked! Enjoy your day!

It works! Thanks a lot!

**Comment by lucasantoiemma** [comment]
Excellent! You're welcome!
