### ISSUE TITLE
Improve Readme Documentation

### ISSUE THREAD

**Issue by trs** [QuorumDMS/ftp-srv#71]
https://github.com/trs/ftp-srv/tree/update-docs

Edit:
This could also include an update collaborator list, maybe in its own file?

**Comment by simonh1000** [comment]
This would help me as I cannot work out how to switch to binary transfers. I tried 
```
ftp.type('I')
```

but that just crashes

**Comment by trs** [comment]
@simonh1000 The transfer type is actually specified by the client by sending the `TYPE` command, per FTP spec.

Check out [RFC 959](https://tools.ietf.org/html/rfc959) for more details (section 3.1.1, page 11)
